#
# This file is part of LitePCIe.
#
# Copyright (c) 2015-2024 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

# In this high level test, LitePCIeEndpoint is connected to LitePCIeDMAReader and LitePCIeDMAWriter
# frontends with Reader's source connected to Writer's sink. Our Host model is used to emulate a Host
# memory with the Reader and Writer are reading/writing data from/to this memory.
#
#                                       ┌───────────┐
#                                       │           │
#                                       │   HOST    │
#                                       │  (Model)  │
#                                       │           │
#                                       └─┬───────▲─┘
#                                         │       │
#                                   ┌─────▼───────┴─────┐
#                                   │                   │
#                                   │                   │
#                                ┌──►  LitePCIeEndpoint ├─┐
#                                │  │                   │ │
#                                │  │                   │ │
#                                │  └───────────────────┘ │
#                                │                        │
#                       ┌────────┴──────────┐   ┌─────────▼─────────┐
#                       │                   │   │                   │
#                       │ LitePCIeDMAWriter │   │ LitePCIeDMAReader │
#                       │                   │   │                   │
#                       └────────▲──────────┘   └─────────┬─────────┘
#                                │                        │
#                                │                        │
#                                └────────────────────────┘
#
# The Host memory  is initially filled with random data, that are read by the Reader, re-directed
# to the Writer and then re-written in another memory location of the Host. The test then checks
# that the initial data and re-written data are identical.

import os
import unittest
from types import SimpleNamespace

import pytest

from litex.gen import *

from litepcie.common import *
from litepcie.core import LitePCIeEndpoint
from litepcie.core.common import LitePCIeMasterInternalPort, LitePCIeMasterPort
from litepcie.core.msi import LitePCIeMSI
from litepcie.frontend.dma import LitePCIeDMAWriter, LitePCIeDMAReader, dma_words_for_bytes
from litepcie.tlp.common import cpl_dict, max_payload_size, max_request_size

from test.common import seed_to_data
from test.model.host import *

# Parameters ---------------------------------------------------------------------------------------

root_id     = 0x100
endpoint_id = 0x400

def _vcd_name(filename):
    return filename if os.environ.get("LITEPCIE_TEST_VCD") else None

# DMA Driver ---------------------------------------------------------------------------------------

class DMADriver:
    """DMA Driver model

    Provides methods to control/program LitePCIeDMAReader/LitePCIeDMAWriter.
    """
    def __init__(self, dma, dut):
        self.dma = getattr(dut, dma)
        self.dut = dut

    def set_prog_mode(self):
        yield from self.dma.table.loop_prog_n.write(0)

    def set_loop_mode(self):
        yield from self.dma.table.loop_prog_n.write(1)

    def flush(self):
        yield from self.dma.table.reset.write(1)

    def program_descriptor(self, address, length):
        address_lsb = (address >>  0) & 0xffff_ffff
        address_msb = (address >> 32) & 0xffff_ffff
        value = address_lsb
        value |= (length << 32)
        yield from self.dma.table.value.write(value)
        yield from self.dma.table.we.write(address_msb)

    def enable(self):
        yield from self.dma._enable.write(1)

    def disable(self):
        yield from self.dma._enable.write(0)

# MSI Handler --------------------------------------------------------------------------------------

DMA_READER_IRQ = 1
DMA_WRITER_IRQ = 2

class MSIHandler(LiteXModule):
    """MSI Handled model

    Handles the MSI IRQs generated by LitePCIeDMAReader/LitePCIeDMAWriter.
    """
    def __init__(self, debug=False):
        self.debug = debug
        self.sink  = stream.Endpoint(msi_layout())

        self.dma_reader_irq_count = 0
        self.dma_writer_irq_count = 0

    def clear_dma_reader_irq_count(self):
        self.dma_reader_irq_count = 0

    def clear_dma_writer_irq_count(self):
        self.dma_writer_irq_count = 0

    @passive
    def generator(self, dut):
        while True:
            yield self.sink.ready.eq(1)
            if (yield self.sink.valid):
                # Get IRQs.
                irq_vector = (yield dut.msi.vector.status)
                irq_clear  = 0

                # Handle IRQs.
                if irq_vector & DMA_READER_IRQ:
                    self.dma_reader_irq_count += 1
                    if self.debug:
                        print("[MSI] dma_reader_irq (n: {:d})".format(self.dma_reader_irq_count))
                    irq_clear |= DMA_READER_IRQ

                if irq_vector & DMA_WRITER_IRQ:
                    self.dma_writer_irq_count += 1
                    if self.debug:
                        print("[MSI] dma_writer_irq (n: {:d})".format(self.dma_writer_irq_count))
                    irq_clear |= DMA_WRITER_IRQ
                # Clear IRQs.
                yield from dut.msi.clear.write((yield from dut.msi.clear.read()) | irq_clear)
            yield

# Test DMA -----------------------------------------------------------------------------------------

@pytest.mark.sim
class TestDMA(unittest.TestCase):
    def test_dma_word_rounding(self):
        self.assertEqual(dma_words_for_bytes(124, 128), 8)
        self.assertEqual(dma_words_for_bytes(128, 128), 8)
        self.assertEqual(dma_words_for_bytes(252, 128), 16)
        self.assertEqual(dma_words_for_bytes(512, 128), 32)

    def test_dma_reader_completion_error_status(self):
        data_width = 128
        captured_data = []

        class DUT(LiteXModule):
            def __init__(self):
                endpoint = SimpleNamespace(
                    phy = SimpleNamespace(
                        data_width       = data_width,
                        max_request_size = max_request_size,
                        max_payload_size = max_payload_size,
                        id               = endpoint_id,
                    ),
                    max_pending_requests = 2,
                )
                internal_port = LitePCIeMasterInternalPort(data_width, channel=0, read_only=True)
                self.port    = LitePCIeMasterPort(internal_port)
                self.reader  = LitePCIeDMAReader(endpoint, self.port, with_table=False)

        dut = DUT()

        @passive
        def monitor_data():
            source = dut.reader.source
            while True:
                yield source.ready.eq(1)
                if (yield source.valid) and (yield source.ready):
                    captured_data.append((yield source.data))
                yield

        def stim():
            desc = dut.reader.desc_sink
            req  = dut.port.source
            cmp  = dut.port.sink

            request_tag = None
            timeout = 0
            while request_tag is None:
                yield req.ready.eq(1)
                yield desc.valid.eq(1)
                yield desc.first.eq(1)
                yield desc.last.eq(1)
                yield desc.address.eq(0)
                yield desc.length.eq(64)
                yield desc.irq_disable.eq(0)
                yield desc.last_disable.eq(0)
                if (yield req.valid) and (yield req.ready):
                    request_tag = (yield req.tag)
                timeout += 1
                if timeout > 64:
                    self.fail("Timed out waiting for DMA Reader request")
                yield

            yield desc.valid.eq(0)
            yield req.ready.eq(0)

            timeout = 0
            while True:
                yield cmp.valid.eq(1)
                yield cmp.first.eq(1)
                yield cmp.last.eq(1)
                yield cmp.req_id.eq(endpoint_id)
                yield cmp.cmp_id.eq(root_id)
                yield cmp.adr.eq(0)
                yield cmp.len.eq(0)
                yield cmp.end.eq(1)
                yield cmp.err.eq(1)
                yield cmp.status.eq(cpl_dict["ca"])
                yield cmp.tag.eq(request_tag)
                yield
                if (yield cmp.ready):
                    break
                timeout += 1
                if timeout > 64:
                    self.fail("Timed out waiting for DMA Reader to accept error completion")

            yield cmp.valid.eq(0)
            yield cmp.first.eq(0)
            yield cmp.last.eq(0)
            for _ in range(8):
                yield

            self.assertEqual((yield dut.reader.enable), 0)
            self.assertEqual((yield dut.reader.error), 1)
            self.assertEqual((yield dut.reader._enable.storage[2]), 1)
            self.assertEqual((yield dut.reader._enable.storage[4:7]), cpl_dict["ca"])
            self.assertEqual((yield dut.reader._enable.storage[24:32]), 1)
            self.assertEqual(captured_data, [])

            yield from dut.reader._enable.write(1)
            for _ in range(4):
                yield

            self.assertEqual((yield dut.reader.enable), 1)
            self.assertEqual((yield dut.reader.error), 0)
            self.assertEqual((yield dut.reader._enable.storage[2]), 0)

            request_tag = None
            timeout = 0
            while request_tag is None:
                yield req.ready.eq(1)
                yield desc.valid.eq(1)
                yield desc.first.eq(1)
                yield desc.last.eq(1)
                yield desc.address.eq(128)
                yield desc.length.eq(64)
                yield desc.irq_disable.eq(0)
                yield desc.last_disable.eq(0)
                if (yield req.valid) and (yield req.ready):
                    request_tag = (yield req.tag)
                timeout += 1
                if timeout > 64:
                    self.fail("Timed out waiting for DMA Reader request after manual restart")
                yield

            yield desc.valid.eq(0)
            yield req.ready.eq(0)

        run_simulation(dut, [stim(), monitor_data()], vcd_name=None)

    def dma_test(self, data_width, address_width, descriptor_lengths=None, test_size=256,
        chipset_split=True, chipset_reordering=True):
        if descriptor_lengths is None:
            descriptor_lengths = [test_size//4] * 4
        test_size = sum(descriptor_lengths)

        host_data     = [seed_to_data(i, True) for i in range(test_size//4)]
        loopback_data = []

        def main_generator(dut):
            # Allocate Host's Memory.
            dut.host.malloc(0x00000000, test_size*2)

            # Enable Chipset
            dut.host.chipset.enable()

            # Fill initial Host's Memory.
            dut.host.write_mem(0x00000000, host_data)

            # DMA Reader/Writer control models.
            dma_reader_driver = DMADriver("dma_reader", dut)
            dma_writer_driver = DMADriver("dma_writer", dut)

            # Program DMA Reader descriptors.
            yield from dma_reader_driver.set_prog_mode()
            yield from dma_reader_driver.flush()
            read_offset = 0
            for length in descriptor_lengths:
                yield from dma_reader_driver.program_descriptor(read_offset, length)
                read_offset += length

            # Program DMA Writer descriptors.
            yield from dma_writer_driver.set_prog_mode()
            yield from dma_writer_driver.flush()
            write_offset = test_size
            for length in descriptor_lengths:
                yield from dma_writer_driver.program_descriptor(write_offset, length)
                write_offset += length

            # Enable MSI.
            yield dut.msi.enable.storage.eq(DMA_READER_IRQ | DMA_WRITER_IRQ)

            # Enable DMA Reader & Writer.
            yield from dma_reader_driver.enable()
            yield from dma_writer_driver.enable()

            # Wait for all writes.
            timeout = 0
            while dut.msi_handler.dma_writer_irq_count != len(descriptor_lengths):
                timeout += 1
                if timeout > 20000:
                    self.fail(
                        f"DMA loopback timed out (width={data_width}, address_width={address_width}, "
                        f"descriptors={descriptor_lengths}, writes={dut.msi_handler.dma_writer_irq_count})"
                    )
                yield

            # Delay to ensure all the data has been written.
            for i in range(1024):
                yield

            for data in dut.host.read_mem(test_size, test_size):
                loopback_data.append(data)


        class DUT(LiteXModule):
            def __init__(self, data_width, address_width):
                self.data_width    = data_width
                self.address_width = address_width

                # Host -----------------------------------------------------------------------------
                self.host = Host(data_width, root_id, endpoint_id,
                    phy_debug          = False,
                    chipset_debug      = False,
                    chipset_split      = chipset_split,
                    chipset_reordering = chipset_reordering,
                    host_debug         = False)

                # Endpoint -------------------------------------------------------------------------
                self.endpoint = LitePCIeEndpoint(self.host.phy,
                    address_width        = address_width,
                    max_pending_requests = 8
                )

                # DMA Reader/Writer ----------------------------------------------------------------
                dma_reader_port = self.endpoint.crossbar.get_master_port(read_only=True)
                dma_writer_port = self.endpoint.crossbar.get_master_port(write_only=True)
                self.dma_reader = LitePCIeDMAReader(self.endpoint, dma_reader_port, address_width=address_width)
                self.dma_writer = LitePCIeDMAWriter(self.endpoint, dma_writer_port, address_width=address_width)
                self.comb += self.dma_reader.source.connect(self.dma_writer.sink)

                # MSI ------------------------------------------------------------------------------
                self.msi = LitePCIeMSI(2)
                self.comb += [
                    self.msi.irqs[log2_int(DMA_READER_IRQ)].eq(self.dma_reader.irq),
                    self.msi.irqs[log2_int(DMA_WRITER_IRQ)].eq(self.dma_writer.irq)
                ]
                self.msi_handler = MSIHandler(debug=False)
                self.comb += self.msi.source.connect(self.msi_handler.sink)

        dut = DUT(data_width, address_width)
        generators = {
            "sys" : [
                main_generator(dut),
                dut.msi_handler.generator(dut),
                dut.host.generator(),
                dut.host.chipset.generator(),
                dut.host.phy.phy_sink.generator(),
                dut.host.phy.phy_source.generator()
            ]
        }
        clocks = {"sys": 10}
        run_simulation(dut, generators, clocks, vcd_name=_vcd_name("test_dma.vcd"))
        self.assertEqual(host_data, loopback_data)

    @pytest.mark.slow
    def test_dma_64b_data_width_32b_address_width(self):
        self.dma_test(data_width=64, address_width=32, test_size=1024)

    @pytest.mark.slow
    def test_dma_64b_data_width_64b_address_width(self):
        self.dma_test(data_width=64, address_width=64)

    @pytest.mark.slow
    def test_dma_128b_data_width_32b_address_width_awkward_lengths(self):
        self.dma_test(
            data_width         = 128,
            address_width      = 32,
            descriptor_lengths = [124, 128, 252, 512],
            chipset_split      = False,
            chipset_reordering = False,
        )

    @pytest.mark.slow
    def test_dma_256b_data_width_32b_address_width(self):
        self.dma_test(data_width=256, address_width=32)

    @pytest.mark.slow
    def test_dma_256b_data_width_64b_address_width(self):
        self.dma_test(data_width=256, address_width=64)

    @pytest.mark.slow
    def test_dma_512b_data_width_32b_address_width(self):
        self.dma_test(data_width=512, address_width=32)

    @pytest.mark.slow
    def test_dma_512b_data_width_64b_address_width(self):
        self.dma_test(data_width=512, address_width=64)
