#
# This file is part of LitePCIe.
#
# Copyright (c) 2015-2024 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

# In this high level test, LitePCIeEndpoint is connected to LitePCIeDMAReader and LitePCIeDMAWriter
# frontends with Reader's source connected to Writer's sink. Our Host model is used to emulate a Host
# memory with the Reader and Writer are reading/writing data from/to this memory.
#
#                                       ┌───────────┐
#                                       │           │
#                                       │   HOST    │
#                                       │  (Model)  │
#                                       │           │
#                                       └─┬───────▲─┘
#                                         │       │
#                                   ┌─────▼───────┴─────┐
#                                   │                   │
#                                   │                   │
#                                ┌──►  LitePCIeEndpoint ├─┐
#                                │  │                   │ │
#                                │  │                   │ │
#                                │  └───────────────────┘ │
#                                │                        │
#                       ┌────────┴──────────┐   ┌─────────▼─────────┐
#                       │                   │   │                   │
#                       │ LitePCIeDMAWriter │   │ LitePCIeDMAReader │
#                       │                   │   │                   │
#                       └────────▲──────────┘   └─────────┬─────────┘
#                                │                        │
#                                │                        │
#                                └────────────────────────┘
#
# The Host memory  is initially filled with random data, that are read by the Reader, re-directed
# to the Writer and then re-written in another memory location of the Host. The test then checks
# that the initial data and re-written data are identical.

import os
import unittest

import pytest

from litex.gen import *

from litepcie.common import *
from litepcie.core import LitePCIeEndpoint
from litepcie.core.msi import LitePCIeMSI
from litepcie.frontend.dma import LitePCIeDMAWriter, LitePCIeDMAReader, dma_words_for_bytes

from test.common import seed_to_data
from test.model.host import *

# Parameters ---------------------------------------------------------------------------------------

root_id     = 0x100
endpoint_id = 0x400

def _vcd_name(filename):
    return filename if os.environ.get("LITEPCIE_TEST_VCD") else None

# DMA Driver ---------------------------------------------------------------------------------------

class DMADriver:
    """DMA Driver model

    Provides methods to control/program LitePCIeDMAReader/LitePCIeDMAWriter.
    """
    def __init__(self, dma, dut):
        self.dma = getattr(dut, dma)
        self.dut = dut

    def set_prog_mode(self):
        yield from self.dma.table.loop_prog_n.write(0)

    def set_loop_mode(self):
        yield from self.dma.table.loop_prog_n.write(1)

    def flush(self):
        yield from self.dma.table.reset.write(1)

    def program_descriptor(self, address, length, last_disable=False):
        address_lsb = (address >>  0) & 0xffff_ffff
        address_msb = (address >> 32) & 0xffff_ffff
        value = address_lsb
        value |= (length << 32)
        value |= (int(last_disable) << 57)
        yield from self.dma.table.value.write(value)
        yield from self.dma.table.we.write(address_msb)

    def enable(self):
        yield from self.dma._enable.write(1)

    def disable(self):
        yield from self.dma._enable.write(0)

# MSI Handler --------------------------------------------------------------------------------------

DMA_READER_IRQ = 1
DMA_WRITER_IRQ = 2

class MSIHandler(LiteXModule):
    """MSI Handled model

    Handles the MSI IRQs generated by LitePCIeDMAReader/LitePCIeDMAWriter.
    """
    def __init__(self, debug=False):
        self.debug = debug
        self.sink  = stream.Endpoint(msi_layout())

        self.dma_reader_irq_count = 0
        self.dma_writer_irq_count = 0

    def clear_dma_reader_irq_count(self):
        self.dma_reader_irq_count = 0

    def clear_dma_writer_irq_count(self):
        self.dma_writer_irq_count = 0

    @passive
    def generator(self, dut):
        while True:
            yield self.sink.ready.eq(1)
            if (yield self.sink.valid):
                # Get IRQs.
                irq_vector = (yield dut.msi.vector.status)
                irq_clear  = 0

                # Handle IRQs.
                if irq_vector & DMA_READER_IRQ:
                    self.dma_reader_irq_count += 1
                    if self.debug:
                        print("[MSI] dma_reader_irq (n: {:d})".format(self.dma_reader_irq_count))
                    irq_clear |= DMA_READER_IRQ

                if irq_vector & DMA_WRITER_IRQ:
                    self.dma_writer_irq_count += 1
                    if self.debug:
                        print("[MSI] dma_writer_irq (n: {:d})".format(self.dma_writer_irq_count))
                    irq_clear |= DMA_WRITER_IRQ
                # Clear IRQs.
                yield from dut.msi.clear.write((yield from dut.msi.clear.read()) | irq_clear)
            yield

# Test DMA -----------------------------------------------------------------------------------------

@pytest.mark.sim
class TestDMA(unittest.TestCase):
    def test_dma_word_rounding(self):
        self.assertEqual(dma_words_for_bytes(124, 128), 8)
        self.assertEqual(dma_words_for_bytes(128, 128), 8)
        self.assertEqual(dma_words_for_bytes(252, 128), 16)
        self.assertEqual(dma_words_for_bytes(512, 128), 32)

    def dma_test(self, data_width, address_width, descriptor_lengths=None, test_size=256,
        chipset_split=True, chipset_reordering=True, dma_data_width=None, check_reader_stream=False,
        reader_last_disable=False):
        if descriptor_lengths is None:
            descriptor_lengths = [test_size//4] * 4
        test_size = sum(descriptor_lengths)
        if isinstance(reader_last_disable, bool):
            reader_last_disable = [reader_last_disable] * len(descriptor_lengths)
        assert len(reader_last_disable) == len(descriptor_lengths)

        host_data     = [seed_to_data(i, True) for i in range(test_size//4)]
        loopback_data = []
        reader_data   = []

        @passive
        def reader_monitor(dut):
            cycle = 0
            yield dut.dma_reader.source.ready.eq(1)
            yield
            while True:
                if (yield dut.dma_reader.source.valid) and (yield dut.dma_reader.source.ready):
                    reader_data.append((
                        (yield dut.dma_reader.source.data),
                        (yield dut.dma_reader.source.last),
                    ))
                # Exercise descriptor delimitation under periodic backpressure.
                yield dut.dma_reader.source.ready.eq((cycle % 4) != 0)
                cycle += 1
                yield

        def main_generator(dut):
            # Allocate Host's Memory.
            dut.host.malloc(0x00000000, test_size*2)

            # Enable Chipset
            dut.host.chipset.enable()

            # Fill initial Host's Memory.
            dut.host.write_mem(0x00000000, host_data)

            # DMA Reader/Writer control models.
            dma_reader_driver = DMADriver("dma_reader", dut)
            if not check_reader_stream:
                dma_writer_driver = DMADriver("dma_writer", dut)

            # Program DMA Reader descriptors.
            yield from dma_reader_driver.set_prog_mode()
            yield from dma_reader_driver.flush()
            read_offset = 0
            for length, last_disable in zip(descriptor_lengths, reader_last_disable):
                yield from dma_reader_driver.program_descriptor(
                    read_offset,
                    length,
                    last_disable=last_disable,
                )
                read_offset += length

            # Program DMA Writer descriptors.
            if not check_reader_stream:
                yield from dma_writer_driver.set_prog_mode()
                yield from dma_writer_driver.flush()
                write_offset = test_size
                for length in descriptor_lengths:
                    yield from dma_writer_driver.program_descriptor(write_offset, length)
                    write_offset += length

            # Enable MSI.
            yield dut.msi.enable.storage.eq(
                DMA_READER_IRQ | (0 if check_reader_stream else DMA_WRITER_IRQ))

            # Enable DMA Reader & Writer.
            yield from dma_reader_driver.enable()
            if not check_reader_stream:
                yield from dma_writer_driver.enable()

            # Wait for all reader words or writes.
            timeout = 0
            stream_width = dma_data_width or data_width
            expected_reader_words = sum(
                dma_words_for_bytes(length, stream_width) for length in descriptor_lengths)
            while ((len(reader_data) < expected_reader_words) if check_reader_stream else
                   (dut.msi_handler.dma_writer_irq_count != len(descriptor_lengths))):
                timeout += 1
                if timeout > 20000:
                    self.fail(
                        f"DMA loopback timed out (width={data_width}, address_width={address_width}, "
                        f"descriptors={descriptor_lengths}, writes={dut.msi_handler.dma_writer_irq_count})"
                    )
                yield

            # Delay to ensure all the data has been written.
            for i in range(1024):
                yield

            if not check_reader_stream:
                for data in dut.host.read_mem(test_size, test_size):
                    loopback_data.append(data)


        class DUT(LiteXModule):
            def __init__(self, data_width, address_width):
                self.data_width    = data_width
                self.address_width = address_width

                # Host -----------------------------------------------------------------------------
                self.host = Host(data_width, root_id, endpoint_id,
                    phy_debug          = False,
                    chipset_debug      = False,
                    chipset_split      = chipset_split,
                    chipset_reordering = chipset_reordering,
                    host_debug         = False)

                # Endpoint -------------------------------------------------------------------------
                self.endpoint = LitePCIeEndpoint(self.host.phy,
                    address_width        = address_width,
                    max_pending_requests = 8
                )

                # DMA Reader/Writer ----------------------------------------------------------------
                dma_reader_port = self.endpoint.crossbar.get_master_port(read_only=True)
                dma_writer_port = self.endpoint.crossbar.get_master_port(write_only=True)
                self.dma_reader = LitePCIeDMAReader(self.endpoint, dma_reader_port,
                    address_width=address_width, data_width=dma_data_width)
                self.dma_writer = LitePCIeDMAWriter(self.endpoint, dma_writer_port,
                    address_width=address_width, data_width=dma_data_width)
                if not check_reader_stream:
                    self.comb += self.dma_reader.source.connect(self.dma_writer.sink)

                # MSI ------------------------------------------------------------------------------
                self.msi = LitePCIeMSI(2)
                self.comb += [
                    self.msi.irqs[log2_int(DMA_READER_IRQ)].eq(self.dma_reader.irq),
                    self.msi.irqs[log2_int(DMA_WRITER_IRQ)].eq(self.dma_writer.irq)
                ]
                self.msi_handler = MSIHandler(debug=False)
                self.comb += self.msi.source.connect(self.msi_handler.sink)

        dut = DUT(data_width, address_width)
        generators = {
            "sys" : [
                main_generator(dut),
                dut.msi_handler.generator(dut),
                dut.host.generator(),
                dut.host.chipset.generator(),
                dut.host.phy.phy_sink.generator(),
                dut.host.phy.phy_source.generator()
            ]
        }
        if check_reader_stream:
            generators["sys"].append(reader_monitor(dut))
        clocks = {"sys": 10}
        run_simulation(dut, generators, clocks, vcd_name=_vcd_name("test_dma.vcd"))
        if not check_reader_stream:
            self.assertEqual(host_data, loopback_data)
        if check_reader_stream:
            stream_width = dma_data_width or data_width
            expected_reader_words = sum(
                dma_words_for_bytes(length, stream_width) for length in descriptor_lengths)
            self.assertEqual(expected_reader_words, len(reader_data))
            expected_last_indices = []
            word_count = 0
            for length, last_disable in zip(descriptor_lengths, reader_last_disable):
                word_count += dma_words_for_bytes(length, stream_width)
                if not last_disable:
                    expected_last_indices.append(word_count - 1)
            self.assertEqual(
                [index for index, (_, last) in enumerate(reader_data) if last],
                expected_last_indices,
            )

    @pytest.mark.slow
    def test_dma_64b_data_width_32b_address_width(self):
        self.dma_test(data_width=64, address_width=32, test_size=1024)

    @pytest.mark.slow
    def test_dma_64b_data_width_64b_address_width(self):
        self.dma_test(data_width=64, address_width=64)

    @pytest.mark.slow
    def test_dma_128b_data_width_32b_address_width_awkward_lengths(self):
        self.dma_test(
            data_width         = 128,
            address_width      = 32,
            descriptor_lengths = [124, 128, 252, 512],
            chipset_split      = False,
            chipset_reordering = False,
        )

    @pytest.mark.slow
    def test_dma_256b_data_width_32b_address_width(self):
        self.dma_test(data_width=256, address_width=32)

    @pytest.mark.slow
    def test_dma_256b_data_width_64b_address_width(self):
        self.dma_test(data_width=256, address_width=64)

    @pytest.mark.slow
    def test_dma_512b_data_width_32b_address_width(self):
        self.dma_test(data_width=512, address_width=32)

    @pytest.mark.slow
    def test_dma_512b_data_width_64b_address_width(self):
        self.dma_test(data_width=512, address_width=64)

    @pytest.mark.slow
    def test_dma_512b_data_width_64b_address_width_32byte_tails(self):
        self.dma_test(
            data_width         = 512,
            address_width      = 64,
            descriptor_lengths = [544, 544],
            chipset_split      = True,
            chipset_reordering = True,
        )

    @pytest.mark.slow
    def test_dma_512b_phy_256b_stream_64b_address_width_32byte_tails(self):
        self.dma_test(
            data_width         = 512,
            dma_data_width     = 256,
            address_width      = 64,
            descriptor_lengths = [544, 544],
            chipset_split      = True,
            chipset_reordering = True,
            check_reader_stream = True,
        )

    @pytest.mark.slow
    def test_dma_reader_last_disable(self):
        self.dma_test(
            data_width         = 512,
            dma_data_width     = 256,
            address_width      = 64,
            descriptor_lengths = [544, 544],
            chipset_split      = True,
            chipset_reordering = True,
            check_reader_stream = True,
            reader_last_disable = [False, True],
        )

    @pytest.mark.slow
    def test_dma_512b_phy_256b_stream_64b_address_width_32byte_tails_loopback(self):
        self.dma_test(
            data_width         = 512,
            dma_data_width     = 256,
            address_width      = 64,
            descriptor_lengths = [544, 544],
            chipset_split      = True,
            chipset_reordering = True,
        )
