#
# This file is part of LitePCIe.
#
# Copyright (c) 2026 blurbdust <blurbdust@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause

"""
Altera/Intel Stratix V PCI Express hard IP (Avalon-ST interface), wrapped for LitePCIe.

Verified on a Microsoft Storey Peak (Azure X930613-001, Stratix V 5SGSMD5): the endpoint enumerates
as 1172:e001 and BAR0 MMIO completes against a Linux host. DMA is not exercised on hardware.
Protocol details cite Intel doc 683093, Stratix V Avalon-ST Interface for PCIe Solutions User Guide.

BAR0 answers 32-bit accesses only, so byte-granular reads abort and return 0xff.

Quartus 25.1std ships no Platform Designer component for this hard IP, so the parameterised top
level `altpcie_sv_hip_ast_hwtcl` is instantiated directly and its sources registered from the
Quartus installation. No pre-generated IP directory is needed. The Transceiver Reconfiguration
Controller (`alt_xcvr_reconfig`) is generated by qsys-generate at build time and cached.

Qword alignment: payload is not packed immediately after the header. The first payload dword sits at
a dword lane whose parity matches address bit 2 of the TLP (doc 683093 s5.2.1, Figure 31). On the
256-bit interface:

    3DW header, address bit2 = 0 : H0 H1 H2 PAD D0 D1 D2 D3   one padding dword
    3DW header, address bit2 = 1 : H0 H1 H2 D0  D1 D2 D3 D4   packed
    4DW header, address bit2 = 0 : H0 H1 H2 H3  D0 D1 D2 D3   packed
    4DW header, address bit2 = 1 : H0 H1 H2 H3  PAD D0 D1 D2  one padding dword

The deciding bit is bit 2 of header dword 2 for 3DW headers and dword 3 for 4DW. Dataless TLPs are
never padded. LitePCIe uses the packed layout only, so `_TXQwordAligner` and `_RXQwordDealigner`
convert at the PHY boundary. `c5pciephy` omits this and the same rule applies to Cyclone V (683666).

Not implemented: Gen3, more than one endpoint (the second hard IP block is disabled in the device,
see https://github.com/ruurdk/sv_second_pcie_hip), `rx_st_be` (byte enables come from `rx_st_empty`
and are qword-granular), `rx_st_mask`, TX parity, hard-IP reconfiguration, CvP, MSI-X and AER.
"""

import os
import re
import shutil
import hashlib
import subprocess

from migen import *

from litex.gen import *

from litex.soc.interconnect import stream
from litex.soc.interconnect.avalon import Native2AvalonST, AvalonST2Native

from litepcie.common import *

# Quartus / Qsys discovery -------------------------------------------------------------------------

def _find_quartus_tool(name, quartus_bindir=None):
    """Locate a Quartus or Qsys binary.

    The Qsys tools live in <quartus>/sopc_builder/bin, which is deliberately *not* on PATH in a
    normal Quartus setup (only <quartus>/quartus/bin is), so searching PATH alone is not enough.
    """
    if quartus_bindir is not None:
        for cand in [
            os.path.join(quartus_bindir, name),
            os.path.join(quartus_bindir, "..", "sopc_builder", "bin", name),
        ]:
            cand = os.path.normpath(cand)
            if os.path.exists(cand):
                return cand
    found = shutil.which(name)
    if found is not None:
        return found

    anchor = shutil.which("quartus_sh") or shutil.which("quartus_map")
    if anchor is not None:
        qbin = os.path.dirname(os.path.realpath(anchor))
        cand = os.path.normpath(os.path.join(qbin, "..", "sopc_builder", "bin", name))
        if os.path.exists(cand):
            return cand

    raise OSError(
        f"Could not find {name}. Qsys tools ship in <quartus>/sopc_builder/bin, which is usually "
        f"not on PATH. Add that directory to PATH, or pass quartus_bindir= to SVPCIEPHY."
    )

def _find_quartus_ip_root(quartus_bindir=None):
    """Return <quartus install>/ip/altera, where the PCIe hard IP sources live."""
    anchor = None
    if quartus_bindir is not None:
        for name in ["quartus_sh", "quartus_map"]:
            cand = os.path.join(quartus_bindir, name)
            if os.path.exists(cand):
                anchor = cand
                break
    if anchor is None:
        anchor = shutil.which("quartus_sh") or shutil.which("quartus_map")
    if anchor is None:
        raise OSError("Could not find Quartus (quartus_sh not on PATH); needed to locate the "
                      "Stratix V PCIe hard IP sources.")
    qbin = os.path.dirname(os.path.realpath(anchor))            # <root>/quartus/bin
    ip   = os.path.normpath(os.path.join(qbin, "..", "..", "ip", "altera"))
    if not os.path.isdir(ip):
        raise OSError(f"Quartus IP directory not found at {ip}.")
    return ip

# Hard IP source files -----------------------------------------------------------------------------

# Synthesis file list that the absent altera_pcie_sv_hip_ast_hw.tcl would have declared. The first
# group is what `altpcie_sv_hip_ast_hwtcl` and `altpcie_hip_256_pipen1b` instantiate; the transceiver
# groups come from Intel's `sv_xcvr_native_fileset.tcl` and `altera_xcvr_generic/ctrl/`.
_HIP_SOURCES = {
    "altera_pcie/altera_pcie_sv_hip_ast" : [
        "altpcie_sv_hip_ast_hwtcl.v",
        "altpcie_hip_256_pipen1b.v",
        "altpcie_rs_hip.v",
        "altpcie_rs_serdes.v",
        "altpcie_hip_eq_bypass_ph3.v",
        "altpcie_hip_eq_dprio.v",
        "altpcie_scfifo.v",
        "altpcie_scfifo_sv.v",
        "altpcie_sv_gbfifo.v",
        "altpcie_sv_scfifo_ext.v",
    ],
    "altera_pcie_pipe/sv" : [
        "sv_xcvr_pipe_native.sv",
        "sv_xcvr_emsip_adapter.sv",
        "sv_xcvr_pipe_nr.sv",
    ],
    "altera_xcvr_generic" : [
        "altera_xcvr_functions.sv",
    ],
    "altera_xcvr_generic/sv" : [
        "sv_pcs.sv", "sv_pcs_ch.sv", "sv_pma.sv",
        "sv_reconfig_bundle_to_xcvr.sv", "sv_reconfig_bundle_to_ip.sv", "sv_reconfig_bundle_merger.sv",
        "sv_rx_pma.sv", "sv_tx_pma.sv", "sv_tx_pma_ch.sv",
        "sv_xcvr_h.sv", "sv_xcvr_avmm_csr.sv", "sv_xcvr_avmm_dcd.sv", "sv_xcvr_avmm.sv",
        "sv_xcvr_data_adapter.sv", "sv_xcvr_native.sv", "sv_xcvr_plls.sv",
    ],
    "altera_xcvr_generic/sv/rbc" : [
        "sv_hssi_10g_rx_pcs_rbc.sv", "sv_hssi_10g_tx_pcs_rbc.sv",
        "sv_hssi_8g_rx_pcs_rbc.sv", "sv_hssi_8g_tx_pcs_rbc.sv",
        "sv_hssi_8g_pcs_aggregate_rbc.sv",
        "sv_hssi_common_pcs_pma_interface_rbc.sv", "sv_hssi_common_pld_pcs_interface_rbc.sv",
        "sv_hssi_pipe_gen1_2_rbc.sv", "sv_hssi_pipe_gen3_rbc.sv",
        "sv_hssi_rx_pcs_pma_interface_rbc.sv", "sv_hssi_rx_pld_pcs_interface_rbc.sv",
        "sv_hssi_tx_pcs_pma_interface_rbc.sv", "sv_hssi_tx_pld_pcs_interface_rbc.sv",
    ],
    "altera_xcvr_generic/ctrl" : [
        "alt_xcvr_resync.sv",
        "alt_xcvr_csr_common_h.sv", "alt_xcvr_csr_common.sv",
        "alt_xcvr_csr_pcs8g_h.sv", "alt_xcvr_csr_pcs8g.sv",
    ],
    # PCIe reconfig driver: drives the Transceiver Reconfiguration Controller.
    "altera_pcie/altera_pcie_hip_ast_ed" : [
        "altpcie_reconfig_driver.sv",
    ],
}

# Timing constraints shipped with the hard IP. Added via platform.add_ip() so LiteX emits
# `set_global_assignment -name SDC_FILE`.
_HIP_SDCS = [
    "altera_pcie/altera_pcie_sv_hip_ast/altera_pcie_sv_hip_ast_pipen1b.sdc",
    "altera_pcie/altera_pcie_sv_hip_ast/altera_pcie_sv_hip_ast_rs_serdes.sdc",
    "altera_pcie/altera_pcie_sv_hip_ast/altera_pcie_sv_hip_ast_enable_power_on_rst_pulse.sdc",
]

def add_hip_sources(platform, quartus_bindir=None):
    ip_root = _find_quartus_ip_root(quartus_bindir)
    for subdir, files in _HIP_SOURCES.items():
        for f in files:
            path = os.path.join(ip_root, subdir, f)
            if not os.path.exists(path):
                raise OSError(
                    f"Stratix V PCIe hard IP source missing: {path}\n"
                    f"This Quartus installation does not carry the Stratix V PCIe IP sources."
                )
            platform.add_source(path)
    for sdc in _HIP_SDCS:
        platform.add_ip(os.path.join(ip_root, sdc))

# Transceiver Reconfiguration Controller generation ------------------------------------------------

# Number of transceiver reconfiguration interfaces, per Intel's Stratix V PCIe example designs
# (<quartus>/ip/altera/altera_pcie/altera_pcie_hip_ast_ed/example_design/sv/pcie_de_*.qsys):
# gen1/gen2 x8 -> 10, gen3 x8 -> 11, and the bus widths are 70 bits per interface towards the
# transceivers and 46 bits back.
def reconfig_interfaces(nlanes, speed):
    per_lane = {1: 2, 4: 5, 8: 10}[nlanes]
    return per_lane + (1 if speed == "gen3" else 0)

def _build_reconfig_qsys_tcl(name, device, family, ninterfaces):
    parameters = {
        "device_family"                 : family,
        "number_of_reconfig_interfaces" : ninterfaces,
        # Offset cancellation is the reason this block is mandatory on Stratix V.
        "enable_offset"                 : 1,
        "enable_dcd"                    : 0,
        "enable_dcd_power_up"           : 1,
        "enable_analog"                 : 0,
        "enable_eyemon"                 : 0,
        "ber_en"                        : 0,
        "enable_dfe"                    : 0,
        "enable_adce"                   : 0,
        "enable_mif"                    : 0,
        "gui_enable_pll"                : 0,
        "gui_cal_status_port"           : "false",
    }
    tcl = [
        "package require -exact qsys 16.0",
        f"create_system {name}",
        f"set_project_property DEVICE_FAMILY {{{family}}}",
        f"set_project_property DEVICE {{{device}}}",
        "add_instance xr alt_xcvr_reconfig",
    ]
    for k in sorted(parameters):
        tcl.append(f"set_instance_parameter_value xr {k} {{{parameters[k]}}}")
    for iname, itype, idir in [
        ("mgmt_clk_clk",       "clock",  "sink"),
        ("mgmt_rst_reset",     "reset",  "sink"),
        ("reconfig_mgmt",      "avalon", "slave"),
        ("reconfig_to_xcvr",   "conduit", "end"),
        ("reconfig_from_xcvr", "conduit", "end"),
        ("reconfig_busy",      "conduit", "end"),
    ]:
        tcl.append(f"add_interface {iname} {itype} {idir}")
        tcl.append(f"set_interface_property {iname} EXPORT_OF xr.{iname}")
    tcl.append(f"save_system {name}.qsys")
    return "\n".join(tcl) + "\n"

def generate_xcvr_reconfig(name, device, family, ninterfaces, output_dir, quartus_bindir=None,
    force=False):
    """Generate an `alt_xcvr_reconfig` Qsys system and return (qip_path, top_verilog_path).

    Cached on a hash of everything that affects the output, like litedram.phy.intel_uniphy.
    """
    tcl = _build_reconfig_qsys_tcl(name, device, family, ninterfaces)
    _CACHE_VERSION = "1"
    hash = hashlib.sha256((_CACHE_VERSION + tcl).encode()).hexdigest()[:16]

    output_dir = os.path.abspath(output_dir)
    os.makedirs(output_dir, exist_ok=True)
    stampfile  = os.path.join(output_dir, f"{name}.litex_hash")
    qip        = os.path.join(output_dir, name, "synthesis", f"{name}.qip")
    top        = os.path.join(output_dir, name, "synthesis", f"{name}.v")

    if not force and os.path.exists(qip) and os.path.exists(top) and os.path.exists(stampfile):
        if open(stampfile).read().strip() == hash:
            print(f"[SVPCIEPHY] Reusing cached transceiver reconfig IP in {output_dir} (hash {hash}).")
            return qip, top

    qsys_script   = _find_quartus_tool("qsys-script",   quartus_bindir)
    qsys_generate = _find_quartus_tool("qsys-generate", quartus_bindir)

    tclfile = os.path.join(output_dir, f"{name}.tcl")
    with open(tclfile, "w") as f:
        f.write(tcl)

    print(f"[SVPCIEPHY] Generating {name} ({ninterfaces} reconfig interfaces) for {device}.")
    for cmd in [
        [qsys_script,   f"--script={name}.tcl"],
        [qsys_generate, f"{name}.qsys", "--synthesis=VERILOG", f"--family={family}",
                        f"--part={device}"],
    ]:
        r = subprocess.run(cmd, cwd=output_dir)
        if r.returncode != 0:
            raise OSError(
                f"[SVPCIEPHY] {os.path.basename(cmd[0])} failed (exit {r.returncode}).\n"
                f"  cmd: {' '.join(cmd)}\n  cwd: {output_dir}\n"
                f"Rerun it by hand there to see the full Qsys log."
            )
    if not os.path.exists(qip):
        raise OSError(f"[SVPCIEPHY] generation reported success but {qip} is missing.")

    with open(stampfile, "w") as f:
        f.write(hash)
    return qip, top

def probe_reconfig_widths(top_verilog):
    """Read back the generated reconfig top level to learn the reconfig bus widths.

    Read rather than recomputed, so a change in Intel's per-interface bus width cannot silently
    produce a mismatched instantiation.
    """
    src = open(top_verilog).read()
    def width(port):
        m = re.search(r"\[\s*(\d+)\s*:\s*0\s*\]\s+" + port, src)
        if m is None:
            raise ValueError(f"Could not find '{port}' in {top_verilog}.")
        return int(m.group(1)) + 1
    return {
        "to"   : width("reconfig_to_xcvr_reconfig_to_xcvr"),
        "from" : width("reconfig_from_xcvr_reconfig_from_xcvr"),
    }

def _int_params_to_32bit(params):
    """Widen integer Instance parameters to 32 bits.

    LiteX emits an integer parameter as a sized literal of exactly the bits it needs, so
    `vendor_id_hwtcl = 0x1172` comes out as `13'd4466`, and a Verilog parameter takes the *width of
    the override*. Intel's RTL then slices `vendor_id_hwtcl[15:0]` and Quartus errors with
    "index 15 cannot fall outside the declared range [12:0]". Emitting 32-bit literals matches what
    an unsized decimal in hand-written Verilog would give.
    """
    for k, v in params.items():
        if k.startswith("p_") and isinstance(v, int) and not isinstance(v, bool):
            params[k] = Constant(v, 32)
    return params

# Qword alignment ----------------------------------------------------------------------------------

def _tlp_needs_pad(header_dw0, header_dw2, header_dw3):
    """Intel's qword-alignment rule, as a Migen expression.

    The first payload dword must land on a dword lane whose parity matches address bit 2, so one
    padding dword is inserted between header and payload when the packed position has the wrong
    parity:

        3DW header (payload would start at lane 3, odd)  -> pad when addr[2] == 0
        4DW header (payload would start at lane 4, even) -> pad when addr[2] == 1

    For 3DW TLPs address bit 2 is bit 2 of header dword 2. That dword holds address[31:2] for memory
    requests and the Lower Address field for completions, and bit 2 is the right bit either way.
    For 4DW TLPs it is bit 2 of header dword 3 (the low half of the 64-bit address).

    Dataless TLPs (reads, completions without data) carry no payload, so they are never padded.
    """
    fmt_has_data = header_dw0[30]
    fmt_4dw      = header_dw0[29]
    return fmt_has_data & Mux(fmt_4dw, header_dw3[2], ~header_dw2[2])


class _TXQwordAligner(LiteXModule):
    """LitePCIe's packed TLP layout -> Intel's qword-aligned Avalon-ST layout.

    Inserts one padding dword after the header when the alignment rule calls for it, shifting the
    rest of the packet up by one dword lane and emitting an extra beat if the packet no longer fits.
    """
    def __init__(self, data_width):
        assert data_width in [128, 256]
        self.sink   = sink   = stream.Endpoint(phy_layout(data_width))
        self.source = source = stream.Endpoint(phy_layout(data_width))

        # # #

        dws = data_width//32

        def dw(sig, i):
            return sig[32*i:32*(i+1)]

        def be(sig, i):
            return sig[4*i:4*(i+1)]

        # Per-packet state.
        shift      = Signal()   # This packet needs the padding dword.
        in_packet  = Signal()   # Past the first beat of the packet.
        carry_dat  = Signal(32, reset_less=True)
        carry_be   = Signal(4,  reset_less=True)
        flush      = Signal()   # Emitting the spilled dword as an extra beat.
        # Dword index of the first lane of the beat currently on `sink`, saturating past the point
        # where the padding dword can be (it is never further in than dword 4).
        beat_base  = Signal(max=2*dws+1)

        # Padding decision and header size, taken from the header on the first beat and held for the
        # rest of the packet.
        pad_now   = Signal()
        hdr_dws   = Signal(max=5)
        hdr_dws_r = Signal(max=5, reset_less=True)
        self.comb += [
            pad_now.eq(_tlp_needs_pad(dw(sink.dat, 0), dw(sink.dat, 2), dw(sink.dat, 3))),
            hdr_dws.eq(Mux(dw(sink.dat, 0)[29], 4, 3)),
        ]

        active_shift = Signal()
        pad_pos      = Signal(max=5)  # Dword index of the padding dword within the packet.
        self.comb += [
            active_shift.eq(Mux(in_packet, shift,     pad_now)),
            pad_pos.eq(     Mux(in_packet, hdr_dws_r, hdr_dws)),
        ]

        # Datapath. Lane i of this beat is dword `beat_base + i` of the packet; everything at or
        # after the padding position moves up by one dword, everything before it stays put. The
        # padding dword lands in the first beat for a 256-bit datapath, and for a 128-bit one in the
        # first beat for 3-dword headers or the second for 4-dword headers.
        out_dat = Signal(data_width)
        out_be  = Signal(data_width//8)
        for i in range(dws):
            src_dat = dw(sink.dat, i-1) if i > 0 else carry_dat
            src_be  = be(sink.be,  i-1) if i > 0 else carry_be
            lane_dw = Signal(max=3*dws+1)
            self.comb += lane_dw.eq(beat_base + i)
            self.comb += [
                If(~active_shift | (lane_dw < pad_pos),
                    # Straight through: before the insertion point, or nothing to insert.
                    dw(out_dat, i).eq(dw(sink.dat, i)),
                    be(out_be,  i).eq(be(sink.be,  i)),
                ).Elif(lane_dw == pad_pos,
                    dw(out_dat, i).eq(0),
                    be(out_be,  i).eq(0xf),
                ).Else(
                    dw(out_dat, i).eq(src_dat),
                    be(out_be,  i).eq(src_be),
                )
            ]

        # The shifted-out top dword spills into an extra beat when the last input beat is full.
        spill = Signal()
        self.comb += spill.eq(active_shift & sink.last & (be(sink.be, dws-1) != 0))

        self.comb += [
            If(flush,
                source.valid.eq(1),
                source.first.eq(0),
                source.last.eq(1),
                dw(source.dat, 0).eq(carry_dat),
                be(source.be,  0).eq(carry_be),
            ).Else(
                source.valid.eq(sink.valid),
                source.first.eq(sink.first),
                source.last.eq(sink.last & ~spill),
                source.dat.eq(out_dat),
                source.be.eq(out_be),
                sink.ready.eq(source.ready),
            )
        ]

        self.sync += [
            If(flush,
                If(source.ready,
                    flush.eq(0),
                    in_packet.eq(0),
                    beat_base.eq(0),
                )
            ).Elif(sink.valid & sink.ready,
                If(sink.first,
                    shift.eq(pad_now),
                    hdr_dws_r.eq(hdr_dws),
                ),
                carry_dat.eq(dw(sink.dat, dws-1)),
                carry_be.eq(be(sink.be,  dws-1)),
                in_packet.eq(~sink.last),
                If(sink.last,
                    flush.eq(spill),
                    beat_base.eq(0),
                ).Elif(beat_base < 2*dws,
                    # Saturates once it is past any possible padding position (dword 4 at most).
                    beat_base.eq(beat_base + dws),
                )
            )
        ]


class _RXQwordDealigner(LiteXModule):
    """Intel's qword-aligned Avalon-ST layout -> LitePCIe's packed TLP layout.

    The exact inverse of _TXQwordAligner: removes the padding dword the hard IP inserted, pulling
    the rest of the packet down by one dword lane. One beat of latency, because the last lane of an
    output beat comes from the first lane of the next input beat.
    """
    def __init__(self, data_width):
        assert data_width in [128, 256]
        self.sink   = sink   = stream.Endpoint(phy_layout(data_width))
        self.source = source = stream.Endpoint(phy_layout(data_width))

        # # #

        dws = data_width//32

        def dw(sig, i):
            return sig[32*i:32*(i+1)]

        def be(sig, i):
            return sig[4*i:4*(i+1)]

        # Buffered input beat.
        buf_dat   = Signal(data_width,    reset_less=True)
        buf_be    = Signal(data_width//8, reset_less=True)
        buf_first = Signal()
        buf_last  = Signal()
        buf_valid = Signal()

        shift = Signal()

        pad_now = Signal()
        self.comb += pad_now.eq(_tlp_needs_pad(dw(buf_dat, 0), dw(buf_dat, 2), dw(buf_dat, 3)))
        hdr_dws = Signal(max=5)
        self.comb += hdr_dws.eq(Mux(dw(buf_dat, 0)[29], 4, 3))

        active_shift = Signal()
        self.comb += active_shift.eq(Mux(buf_first, pad_now, shift))

        # Emit the buffered beat once the next beat's first dword is available, unless it is the
        # last beat or nothing is being shifted. Byte enables are qword-granular, so a last beat
        # carries at least two dwords and the shift cannot leave a trailing empty beat.
        self.comb += [
            source.valid.eq(buf_valid & (sink.valid | buf_last | ~active_shift)),
            source.first.eq(buf_first),
            source.last.eq(buf_last),
        ]
        for i in range(dws):
            nxt_dat = dw(sink.dat, 0) if i == dws-1 else dw(buf_dat, i+1)
            nxt_be  = be(sink.be,  0) if i == dws-1 else be(buf_be,  i+1)
            if i == dws-1:
                nxt_dat = Mux(buf_last, 0, nxt_dat)
                nxt_be  = Mux(buf_last, 0, nxt_be)
            self.comb += [
                If(~active_shift,
                    dw(source.dat, i).eq(dw(buf_dat, i)),
                    be(source.be,  i).eq(be(buf_be,  i)),
                ).Elif(buf_first & (i < hdr_dws),
                    # Header dwords are not moved.
                    dw(source.dat, i).eq(dw(buf_dat, i)),
                    be(source.be,  i).eq(be(buf_be,  i)),
                ).Else(
                    dw(source.dat, i).eq(nxt_dat),
                    be(source.be,  i).eq(nxt_be),
                )
            ]

        # Input side: accept a beat whenever the buffer is free or is being emitted. When the
        # buffered beat is not the last one, the *next* beat is consumed by the emission of the
        # buffered one only in the sense of being sampled; it is still needed in full, so it is
        # simply loaded into the buffer.
        self.comb += sink.ready.eq(~buf_valid | (source.valid & source.ready))

        self.sync += [
            If(sink.valid & sink.ready,
                buf_dat.eq(sink.dat),
                buf_be.eq(sink.be),
                buf_first.eq(sink.first),
                buf_last.eq(sink.last),
                buf_valid.eq(1),
                If(sink.first,
                    shift.eq(_tlp_needs_pad(dw(sink.dat, 0), dw(sink.dat, 2), dw(sink.dat, 3))),
                ),
            ).Elif(source.valid & source.ready,
                buf_valid.eq(0),
            )
        ]

# SVPCIEPHY ----------------------------------------------------------------------------------------

class SVPCIEPHY(LiteXModule):
    endianness    = "little"
    qword_aligned = False # The alignment is undone inside this PHY, so the rest of LitePCIe sees
                          # the ordinary packed layout.

    def __init__(self, platform, pads, data_width=256, cd="sys",
        # Link configuration.
        speed          = "gen2",   # "gen1" or "gen2".
        nlanes         = 8,
        # PCIe hard block parameters.
        bar0_size      = 0x100000,
        vendor_id      = 0x1172,   # Altera.
        device_id      = 0xe001,
        revision_id    = 0x00,   # LitePCIe's kernel driver rejects any non-zero PCI revision.
        class_code     = 0xff0000, # Unassigned class.
        subsys_vendor_id = 0x1172,
        subsys_device_id = 0xe001,
        max_payload_size = 256,
        # Quartus release the IP is parameterised for. Only needs changing on a Quartus whose
        # Stratix V PCIe IP expects a different value; validated on 25.1std.
        acds_version   = "25.1",
        # Clocking.
        mgmt_clk       = None,     # Transceiver Reconfiguration Controller clock (see below).
        mgmt_rst       = None,
        mgmt_clk_name  = None,     # Its SDC clock name, if it is not `cd`'s (for timing cuts).
        # Toolchain.
        device         = None,
        family         = "Stratix V",
        name           = "svpcie_xcvr_reconfig",
        output_dir     = None,
        quartus_bindir = None,
    ):
        # Streams ---------------------------------------------------------------------------------
        self.sink   = stream.Endpoint(phy_layout(data_width))
        self.source = stream.Endpoint(phy_layout(data_width))
        self.msi    = stream.Endpoint(msi_layout())

        # Parameters/Locals ------------------------------------------------------------------------
        self.pads             = pads
        self.platform         = platform
        self.data_width       = data_width

        self.id               = Signal(16, reset_less=True)
        self.bar0_size        = bar0_size
        self.bar0_mask        = get_bar_mask(bar0_size)
        self.max_request_size = Signal(16, reset_less=True)
        self.max_payload_size = Signal(16, reset_less=True)

        self.external_hard_ip = False

        # Checks -----------------------------------------------------------------------------------
        assert speed in ["gen1", "gen2"]
        assert nlanes in [1, 4, 8]
        # Application clock is coreclkout_hip. The legal {speed, lanes, width} combinations and the
        # resulting coreclkout_hip frequency are tabulated in Intel doc 683093 Table 67
        # ("Application Clock Frequency" / coreclkout_hip). Kept here: only the combinations that
        # give a 125 MHz or 250 MHz application clock.
        supported = {
            ("gen1", 1) : [64],
            ("gen1", 4) : [64, 128],
            ("gen1", 8) : [64, 128, 256],
            ("gen2", 1) : [64],
            ("gen2", 4) : [64, 128, 256],
            ("gen2", 8) : [128, 256],
        }[(speed, nlanes)]
        if data_width not in supported:
            raise ValueError(f"SVPCIEPHY: data_width={data_width} is not supported for "
                             f"{speed} x{nlanes} (supported: {supported}).")
        if data_width == 64:
            raise ValueError(
                "SVPCIEPHY: the 64-bit Avalon-ST width is not supported by this PHY. Intel's qword "
                "alignment rule then spans two beats and the aligners here are 128/256-bit only. "
                "Use 128 or 256.")

        device = device if device is not None else platform.device
        if output_dir is None:
            output_dir = os.path.join(os.getcwd(), "build", "svpcie_ip")

        # Application clock frequency, for reference/constraints.
        #   coreclkout_hip = link_rate * nlanes / data_width
        link_rate  = {"gen1": 2.5e9*0.8, "gen2": 5.0e9*0.8}[speed]
        self.pcie_clk_freq = link_rate*nlanes/data_width

        # # #

        # Clock domains ----------------------------------------------------------------------------
        self.cd_pcie = ClockDomain()

        coreclkout_hip = Signal()
        reset_status   = Signal()
        self.comb += [
            self.cd_pcie.clk.eq(coreclkout_hip),
            self.cd_pcie.rst.eq(reset_status),
        ]

        # The Transceiver Reconfiguration Controller needs a free-running 100-125 MHz clock and must
        # be alive before the transceivers it calibrates (doc 683093 s16.1). Defaults to `cd`, so
        # keep that domain in range or pass a clock.
        if mgmt_clk is None:
            mgmt_clk = ClockSignal(cd)
        if mgmt_rst is None:
            mgmt_rst = ResetSignal(cd)

        # Hard IP sources --------------------------------------------------------------------------
        add_hip_sources(platform, quartus_bindir)

        # Transceiver Reconfiguration Controller ----------------------------------------------------
        ninterfaces = reconfig_interfaces(nlanes, speed)
        qip, top    = generate_xcvr_reconfig(
            name           = name,
            device         = device,
            family         = family,
            ninterfaces    = ninterfaces,
            output_dir     = output_dir,
            quartus_bindir = quartus_bindir,
        )
        platform.add_ip(qip)
        # Intel's reconfig driver does `import alt_xcvr_reconfig_h::*`, but the .qip compiles that
        # package into the generated system's own Verilog library, where the driver (which sits in
        # the default library alongside the rest of the design) cannot see it. Add the package to
        # the default library as well; a package may be declared in more than one library.
        platform.add_source(os.path.join(os.path.dirname(qip), "submodules",
                                         "alt_xcvr_reconfig_h.sv"))
        widths = probe_reconfig_widths(top)

        reconfig_to_xcvr   = Signal(widths["to"])
        reconfig_from_xcvr = Signal(widths["from"])
        reconfig_busy      = Signal()

        reconfig_mgmt_address     = Signal(7)
        reconfig_mgmt_read        = Signal()
        reconfig_mgmt_readdata    = Signal(32)
        reconfig_mgmt_waitrequest = Signal()
        reconfig_mgmt_write       = Signal()
        reconfig_mgmt_writedata   = Signal(32)

        self.specials += Instance(name,
            i_mgmt_clk_clk_clk                      = mgmt_clk,
            i_mgmt_rst_reset_reset                  = mgmt_rst,
            o_reconfig_busy_reconfig_busy           = reconfig_busy,
            i_reconfig_from_xcvr_reconfig_from_xcvr = reconfig_from_xcvr,
            o_reconfig_to_xcvr_reconfig_to_xcvr     = reconfig_to_xcvr,
            i_reconfig_mgmt_address                 = reconfig_mgmt_address,
            i_reconfig_mgmt_read                    = reconfig_mgmt_read,
            o_reconfig_mgmt_readdata                = reconfig_mgmt_readdata,
            o_reconfig_mgmt_waitrequest             = reconfig_mgmt_waitrequest,
            i_reconfig_mgmt_write                   = reconfig_mgmt_write,
            i_reconfig_mgmt_writedata               = reconfig_mgmt_writedata,
        )

        # PCIe reconfig driver ----------------------------------------------------------------------
        # Intel's own driver for the controller above; the hard IP's status signals it watches are
        # connected as in their example design.
        currentspeed = Signal(2)
        hip_status   = {
            "derr_cor_ext_rcv" : Signal(),
            "derr_cor_ext_rpl" : Signal(),
            "derr_rpl"         : Signal(),
            "dlup"             : Signal(),
            "dlup_exit"        : Signal(),
            "ev128ns"          : Signal(),
            "ev1us"            : Signal(),
            "hotrst_exit"      : Signal(),
            "int_status"       : Signal(4),
            "l2_exit"          : Signal(),
            "lane_act"         : Signal(4),
            "ltssmstate"       : Signal(5),
            "rx_par_err"       : Signal(),
            "tx_par_err"       : Signal(2),
            "cfg_par_err"      : Signal(),
            "ko_cpl_spc_header": Signal(8),
            "ko_cpl_spc_data"  : Signal(12),
        }
        self.hip_status = hip_status

        self.specials += Instance("altpcie_reconfig_driver",
            p_number_of_reconfig_interfaces = Constant(ninterfaces, 32),
            p_gen123_lane_rate_mode_hwtcl   = {"gen1": "Gen1 (2.5 Gbps)",
                                               "gen2": "Gen2 (5.0 Gbps)"}[speed],
            p_INTENDED_DEVICE_FAMILY        = family,

            i_pld_clk                 = ClockSignal("pcie"),
            i_reconfig_xcvr_rst       = mgmt_rst,
            i_reconfig_xcvr_clk       = mgmt_clk,
            i_reconfig_busy           = reconfig_busy,
            o_cal_busy_in             = Signal(),

            o_reconfig_mgmt_address   = reconfig_mgmt_address,
            o_reconfig_mgmt_read      = reconfig_mgmt_read,
            i_reconfig_mgmt_readdata  = reconfig_mgmt_readdata,
            i_reconfig_mgmt_waitrequest = reconfig_mgmt_waitrequest,
            o_reconfig_mgmt_write     = reconfig_mgmt_write,
            o_reconfig_mgmt_writedata = reconfig_mgmt_writedata,

            i_currentspeed            = currentspeed,
            **{f"i_{k}_drv": v for k, v in hip_status.items()},
        )

        # TX CDC (FPGA --> HOST) -------------------------------------------------------------------
        if cd == "pcie":
            tx_st = self.sink
        else:
            tx_buffer = stream.Buffer(phy_layout(data_width))
            tx_buffer = ClockDomainsRenamer(cd)(tx_buffer)
            tx_cdc    = stream.AsyncFIFO(phy_layout(data_width), 32)
            tx_cdc    = ClockDomainsRenamer({"write": cd, "read": "pcie"})(tx_cdc)
            self.submodules += tx_buffer, tx_cdc
            self.comb += [
                self.sink.connect(tx_buffer.sink),
                tx_buffer.source.connect(tx_cdc.sink),
            ]
            tx_st = tx_cdc.source

        # RX CDC (HOST --> FPGA) -------------------------------------------------------------------
        if cd == "pcie":
            rx_st = self.source
        else:
            rx_cdc    = stream.AsyncFIFO(phy_layout(data_width), 32)
            rx_cdc    = ClockDomainsRenamer({"write": "pcie", "read": cd})(rx_cdc)
            rx_buffer = stream.Buffer(phy_layout(data_width))
            rx_buffer = ClockDomainsRenamer(cd)(rx_buffer)
            self.submodules += rx_buffer, rx_cdc
            self.comb += [
                rx_cdc.source.connect(rx_buffer.sink),
                rx_buffer.source.connect(self.source),
            ]
            rx_st = rx_cdc.sink

        # MSI CDC (FPGA --> HOST) ------------------------------------------------------------------
        if cd == "pcie":
            cfg_msi = self.msi
        else:
            msi_cdc = stream.AsyncFIFO(msi_layout(), 4)
            msi_cdc = ClockDomainsRenamer({"write": cd, "read": "pcie"})(msi_cdc)
            self.submodules += msi_cdc
            self.comb += self.msi.connect(msi_cdc.sink)
            cfg_msi = msi_cdc.source

        # Configuration space decode ----------------------------------------------------------------
        # tl_cfg_ctl is a 32-bit window multiplexed over 16 addresses selected by tl_cfg_add. There
        # is no write strobe on Stratix V, so the address is watched for a change and the data
        # sampled mid-window (doc 683093 s5.13.1). Field mapping is Figure 55 of the same doc.
        tl_cfg_add = Signal(4)
        tl_cfg_ctl = Signal(32)

        def convert_size(command, size):
            cases = {}
            value = 128
            for i in range(6):
                cases[i] = size.eq(value)
                value = value*2
            return Case(command, cases)

        bus_number      = Signal(8)
        device_number   = Signal(5)
        function_number = Signal(3)
        dcommand        = Signal(16)

        self.bus_number      = bus_number
        self.device_number   = device_number
        self.function_number = function_number

        cfg_add_reg     = Signal(4)
        cfg_add_reg2    = Signal(4)
        cfg_data_reg    = Signal(32)
        addr_change     = Signal()
        addr_change2    = Signal()
        addr_strobe     = Signal()
        captured_addr   = Signal(4)
        captured_data   = Signal(32)

        self.sync.pcie += [
            cfg_add_reg.eq(tl_cfg_add),
            cfg_add_reg2.eq(cfg_add_reg),
            cfg_data_reg.eq(tl_cfg_ctl),

            addr_change.eq(cfg_add_reg != cfg_add_reg2),
            addr_change2.eq(addr_change),
            addr_strobe.eq(addr_change2),

            If(addr_strobe,
                captured_addr.eq(cfg_add_reg),
                captured_data.eq(cfg_data_reg),
            ),
        ]

        self.sync.pcie += [
            # tl_cfg_add == 0 : Device Control register in bits [31:16] (cfg_devcsr[15:0]).
            If(captured_addr == 0x0,
                dcommand.eq(captured_data[16:32]),
            ),
            # tl_cfg_add == 15 : cfg_busdev[12:0] = {bus[7:0], device[4:0]}.
            If(captured_addr == 0xf,
                device_number.eq(captured_data[0:5]),
                bus_number.eq(captured_data[5:13]),
            ),
        ]

        self.sync.pcie += [
            convert_size(dcommand[5:8],   self.max_payload_size),
            convert_size(dcommand[12:15], self.max_request_size),
            self.id.eq(Cat(function_number, device_number, bus_number)),
        ]
        # Only one function is enabled on the hard IP, so the function number is always 0.
        self.comb += function_number.eq(0)

        # Qword alignment + native <-> Avalon-ST --------------------------------------------------
        tx_align = ClockDomainsRenamer("pcie")(_TXQwordAligner(data_width))
        rx_align = ClockDomainsRenamer("pcie")(_RXQwordDealigner(data_width))
        self.submodules += tx_align, rx_align

        # Avalon-ST readyLatency, from the Stratix V Avalon-ST PCIe user guide (Intel doc 683093):
        # the RX interface "supports a readyLatency of 3 cycles" (raised from 2 in v18.0; older
        # copies of the guide say 2, and its own figures are inconsistent, so size for 3), while for
        # TX "Intel recommends a readyLatency of 2 cycles to facilitate timing closure".
        tx_n2av = ClockDomainsRenamer("pcie")(Native2AvalonST(phy_layout(data_width), latency=2))
        rx_av2n = ClockDomainsRenamer("pcie")(AvalonST2Native(phy_layout(data_width), latency=3))
        self.submodules += tx_n2av, rx_av2n

        self.comb += [
            tx_st.connect(tx_align.sink),
            tx_align.source.connect(tx_n2av.sink),

            rx_av2n.source.connect(rx_align.sink),
            rx_align.source.connect(rx_st),
        ]

        tx_avst = tx_n2av.source
        rx_avst = rx_av2n.sink

        # Avalon-ST `empty` is the number of unused *qwords* in the final beat of a packet; the
        # dwords within a partially used qword are implied by the TLP's length field. Derived from
        # the byte enables so it stays consistent with the datapath.
        nqwords    = data_width//64
        tx_empty   = Signal(max=max(nqwords, 2))
        qword_used = Signal(nqwords)
        self.comb += [
            [qword_used[q].eq(tx_avst.be[8*q:8*(q+1)] != 0) for q in range(nqwords)],
        ]
        self.comb += Case(Cat(*[qword_used[q] for q in range(nqwords)]), {
            **{(1 << (q+1))-1 : tx_empty.eq(nqwords-1-q) for q in range(nqwords)},
            "default" : tx_empty.eq(0),
        })

        # Byte enables come from rx_st_empty, not rx_st_be: the latter is deprecated and "only
        # applies to PCI Express Memory Write and I/O Write TLP payload fields", so it reads zero for
        # completion payloads. rx_st_empty counts unused qwords and is valid only with rx_st_eop, so
        # an odd trailing dword shows up as valid and is discarded downstream via the length field.
        rx_empty = Signal(2)
        self.comb += [
            rx_avst.be.eq(2**(data_width//8)-1),
            If(rx_avst.last,
                Case(rx_empty, {q : rx_avst.be.eq(2**(data_width//8 - 8*q)-1)
                                for q in range(nqwords)}),
            ),
        ]

        # Hard IP -----------------------------------------------------------------------------------
        pcie_refclk = Signal()
        self.comb += pcie_refclk.eq(pads.clk_p)

        serdes_pll_locked = Signal()

        self.hip_params = dict(
            # Link.
            p_lane_mask_hwtcl             = f"x{nlanes}",
            p_gen123_lane_rate_mode_hwtcl = {"gen1": "Gen1 (2.5 Gbps)",
                                             "gen2": "Gen2 (5.0 Gbps)"}[speed],
            p_port_type_hwtcl             = "Native endpoint",
            p_pcie_spec_version_hwtcl     = "2.1",
            p_pll_refclk_freq_hwtcl       = "100 MHz",

            # Avalon-ST.
            p_ast_width_hwtcl             = f"Avalon-ST {data_width}-bit",
            p_port_width_data_hwtcl       = data_width,
            p_port_width_be_hwtcl         = data_width//8,
            p_multiple_packets_per_cycle_hwtcl = 0,
            p_use_ast_parity              = 0,

            # Reconfiguration buses.
            p_reconfig_to_xcvr_width      = widths["to"],
            p_reconfig_from_xcvr_width    = widths["from"],
            p_hip_reconfig_hwtcl          = 0,

            # BAR0 only, 64-bit, non-prefetchable.
            p_bar0_io_space_hwtcl         = "Disabled",
            p_bar0_64bit_mem_space_hwtcl  = "Enabled",
            p_bar0_prefetchable_hwtcl     = "Disabled",
            p_bar0_size_mask_hwtcl        = log2_int(bar0_size),

            # Identity.
            p_vendor_id_hwtcl             = vendor_id,
            p_device_id_hwtcl             = device_id,
            p_revision_id_hwtcl           = revision_id,
            p_class_code_hwtcl            = class_code,
            p_subsystem_vendor_id_hwtcl   = subsys_vendor_id,
            p_subsystem_device_id_hwtcl   = subsys_device_id,
            p_max_payload_size_hwtcl      = max_payload_size,

            # MSI: one vector, no MSI-X.
            p_msi_support_hwtcl           = "true",
            p_msi_multi_message_capable_hwtcl = "count_1",
            p_msi_64bit_addressing_capable_hwtcl = "true",
            p_enable_function_msix_support_hwtcl = 0,

            # Reset. Quartus rejects the hard reset controller at Gen2 ("Hard Reset Controller can
            # not be enabled for protocol mode 'pipe_g2'"). The hard IP only honours
            # enable_power_on_rst_pulse when the hard reset controller is off.
            p_hip_hard_reset_hwtcl        = 0,
            p_enable_power_on_rst_pulse_hwtcl = 1,

            p_ACDS_VERSION_HWTCL          = acds_version,

            # Clocks.
            i_refclk                      = pcie_refclk,
            i_pld_clk                     = ClockSignal("pcie"),
            o_coreclkout_hip              = coreclkout_hip,

            # Resets / status.
            i_npor                        = ~ResetSignal(cd) & pads.perst_n,
            i_pin_perst                   = pads.perst_n,
            o_reset_status                = reset_status,
            o_serdes_pll_locked           = serdes_pll_locked,
            i_pld_core_ready              = serdes_pll_locked,
            o_pld_clk_inuse               = Signal(),
            o_testin_zero                 = Signal(),

            # Test/simulation control. test_in is not zero in hardware: doc 683093 specifies
            # hip_ctrl_test_in = 32'h188, with bits 0 and 2 clear for hardware, bits [4:3] reserved
            # at 2'b01 and bit 7 disabling low power state negotiation.
            i_test_in                     = 0x188,
            i_simu_mode_pipe              = 0,
            i_reservedin                  = 0,
            i_sim_pipe_pclk_in            = 0,
            i_hpg_ctrler                  = 0,

            # Transceiver reconfiguration.
            i_reconfig_to_xcvr            = reconfig_to_xcvr,
            o_reconfig_from_xcvr          = reconfig_from_xcvr,

            # Config space.
            o_tl_cfg_add                  = tl_cfg_add,
            o_tl_cfg_ctl                  = tl_cfg_ctl,

            # Status (to the reconfig driver).
            o_currentspeed                = currentspeed,
            **{f"o_{k}": v for k, v in hip_status.items()},

        )

        self.hip_params.update(
            # RX Avalon-ST.
            o_rx_st_valid                 = rx_avst.valid,
            o_rx_st_sop                   = rx_avst.first,
            o_rx_st_eop                   = rx_avst.last,
            i_rx_st_ready                 = rx_avst.ready,
            o_rx_st_data                  = rx_avst.dat,
            o_rx_st_empty                 = rx_empty,
            i_rx_st_mask                  = 0,

            # TX Avalon-ST.
            i_tx_st_valid                 = tx_avst.valid,
            i_tx_st_sop                   = tx_avst.first,
            i_tx_st_eop                   = tx_avst.last,
            o_tx_st_ready                 = tx_avst.ready,
            i_tx_st_data                  = tx_avst.dat,
            i_tx_st_empty                 = tx_empty,
            i_tx_st_err                   = 0,
            i_tx_st_parity                = 0,

            # Completion / error reporting: unused.
            i_cpl_err                     = 0,
            i_cpl_pending                 = 0,

            # Local Management Interface: unused.
            i_lmi_addr                    = 0,
            i_lmi_din                     = 0,
            i_lmi_rden                    = 0,
            i_lmi_wren                    = 0,

            # Power management: unused.
            i_pm_auxpwr                   = 0,
            i_pm_data                     = 0,
            i_pme_to_cr                   = 0,
            i_pm_event                    = 0,

            # MSI.
            i_app_msi_req                 = cfg_msi.valid,
            o_app_msi_ack                 = cfg_msi.ready,
            i_app_msi_num                 = 0,
            i_app_msi_tc                  = 0,
            i_aer_msi_num                 = 0,
            i_pex_msi_num                 = 0,
            i_app_int_sts                 = 0,

            # Credit / config bypass: unused.
            i_tx_cons_cred_sel            = 0,

            # Hard IP reconfiguration (DPRIO): unused.
            i_hip_reconfig_rst_n          = 0,
            i_hip_reconfig_clk            = 0,
            i_hip_reconfig_write          = 0,
            i_hip_reconfig_read           = 0,
            i_hip_reconfig_byte_en        = 0,
            i_hip_reconfig_address        = 0,
            i_hip_reconfig_writedata      = 0,
            i_ser_shift_load              = 0,
            i_interface_sel               = 0,
        )

        # Serial lanes.
        for i in range(nlanes):
            self.hip_params[f"i_rx_in{i}"]  = pads.rx_p[i]
            self.hip_params[f"o_tx_out{i}"] = pads.tx_p[i]

        # Constraints -------------------------------------------------------------------------------
        # coreclkout_hip comes from the hard IP's own PLL and is unrelated to the SoC clocks; every
        # crossing here is through an async FIFO or a MultiReg. `derive_pll_clocks` names it after
        # its hierarchy position, so LiteX's `add_false_path_constraints()` emits
        # `set_false_path -from [get_clocks {pcie_clk}]`, which matches nothing. Hence the wildcards.
        # Only the application clock is cut: the transceiver reconfiguration bundle carries the
        # management clock into the transceivers' AVMM blocks and those transfers are synchronous.
        pcie_core_clk = "*|coreclkout_hip"
        for name in [f"{cd}_clk"] + ([mgmt_clk_name] if mgmt_clk_name is not None else []):
            platform.toolchain.additional_sdc_commands += [
                f"set_false_path -from [get_clocks {{{name}}}] -to [get_clocks {{{pcie_core_clk}}}]",
                f"set_false_path -from [get_clocks {{{pcie_core_clk}}}] -to [get_clocks {{{name}}}]",
            ]

        # The reconfiguration controller's own SDC ends with a loop that makes each transceiver
        # pmatestbussel[0] clock asynchronous to everything else. That loop needs the clocks to
        # exist when it runs, which its header states means it must be read after derive_pll_clocks:
        # "The derive_pll_clocks constraint needs to be run before the following constraints are
        # read, or certain constraints may be ignored." LiteX emits its SDC after every QIP_FILE, so
        # the collection is empty there and the grouping is silently skipped, leaving the AVMM read
        # path from the transceivers to the controller timed against the management clock. Repeating
        # the loop here runs it once the clocks exist.
        platform.toolchain.additional_sdc_commands += [
            "foreach_in_collection c [get_clocks {*hssi_avmm_interface_inst|pmatestbussel[0]}] {",
            "    set_clock_groups -asynchronous -group [get_clock_info -name $c]",
            "}",
        ]

        # Constrain the 100 MHz PCIe reference clock at the pin, otherwise the transceiver PLL has
        # no base clock and `coreclkout_hip` is unconstrained. Intel's example SDC uses
        # `derive_pll_clocks -create_base_clocks`; LiteX emits `-use_net_name`, and derive_pll_clocks
        # must only be applied once per project, so the base clock is declared here instead.
        platform.add_period_constraint(pads.clk_p, 1e9/100e6)

        # Timing analysis of transceiver-derived clocks is meaningless without this, and Quartus
        # only warns if it is missing. Guarded because litedram's UniPHY wrapper adds it too and it
        # must not be issued twice.
        if "derive_clock_uncertainty" not in platform.toolchain.additional_sdc_commands:
            platform.toolchain.additional_sdc_commands.append("derive_clock_uncertainty")

    def do_finalize(self):
        self.specials += Instance("altpcie_sv_hip_ast_hwtcl", **_int_params_to_32bit(self.hip_params))
