#ifndef __GENERATED_CSR_H
#define __GENERATED_CSR_H

/* crg */
#define CSR_CRG_BASE 0x0
#define CSR_CRG_SOFT_RST_ADDR 0x0
#define CSR_CRG_SOFT_RST_SIZE 1
#define CSR_CRG_SCRATCH_ADDR 0x4
#define CSR_CRG_SCRATCH_SIZE 1

/* dma */
#define CSR_DMA_BASE 0x9000
#define CSR_DMA_WRITER_ENABLE_ADDR 0x9000
#define CSR_DMA_WRITER_ENABLE_SIZE 1
#define CSR_DMA_WRITER_TABLE_VALUE_ADDR 0x9004
#define CSR_DMA_WRITER_TABLE_VALUE_SIZE 2
#define CSR_DMA_WRITER_TABLE_WE_ADDR 0x900c
#define CSR_DMA_WRITER_TABLE_WE_SIZE 1
#define CSR_DMA_WRITER_TABLE_LOOP_PROG_N_ADDR 0x9010
#define CSR_DMA_WRITER_TABLE_LOOP_PROG_N_SIZE 1
#define CSR_DMA_WRITER_TABLE_LOOP_STATUS_ADDR 0x9014
#define CSR_DMA_WRITER_TABLE_LOOP_STATUS_SIZE 1
#define CSR_DMA_WRITER_TABLE_LEVEL_ADDR 0x9018
#define CSR_DMA_WRITER_TABLE_LEVEL_SIZE 1
#define CSR_DMA_WRITER_TABLE_FLUSH_ADDR 0x901c
#define CSR_DMA_WRITER_TABLE_FLUSH_SIZE 1
#define CSR_DMA_READER_ENABLE_ADDR 0x9020
#define CSR_DMA_READER_ENABLE_SIZE 1
#define CSR_DMA_READER_TABLE_VALUE_ADDR 0x9024
#define CSR_DMA_READER_TABLE_VALUE_SIZE 2
#define CSR_DMA_READER_TABLE_WE_ADDR 0x902c
#define CSR_DMA_READER_TABLE_WE_SIZE 1
#define CSR_DMA_READER_TABLE_LOOP_PROG_N_ADDR 0x9030
#define CSR_DMA_READER_TABLE_LOOP_PROG_N_SIZE 1
#define CSR_DMA_READER_TABLE_LOOP_STATUS_ADDR 0x9034
#define CSR_DMA_READER_TABLE_LOOP_STATUS_SIZE 1
#define CSR_DMA_READER_TABLE_LEVEL_ADDR 0x9038
#define CSR_DMA_READER_TABLE_LEVEL_SIZE 1
#define CSR_DMA_READER_TABLE_FLUSH_ADDR 0x903c
#define CSR_DMA_READER_TABLE_FLUSH_SIZE 1
#define CSR_DMA_LOOPBACK_ENABLE_ADDR 0x9040
#define CSR_DMA_LOOPBACK_ENABLE_SIZE 1

/* identifier */
#define CSR_IDENTIFIER_BASE 0x1800
#define CSR_IDENTIFIER_SYSID_ADDR 0x1800
#define CSR_IDENTIFIER_SYSID_SIZE 1
#define CSR_IDENTIFIER_REVISION_ADDR 0x1804
#define CSR_IDENTIFIER_REVISION_SIZE 1
#define CSR_IDENTIFIER_FREQUENCY_ADDR 0x1808
#define CSR_IDENTIFIER_FREQUENCY_SIZE 1

/* irq_controller */
#define CSR_IRQ_CONTROLLER_BASE 0x9800
#define CSR_IRQ_CONTROLLER_ENABLE_ADDR 0x9800
#define CSR_IRQ_CONTROLLER_ENABLE_SIZE 1
#define CSR_IRQ_CONTROLLER_CLEAR_ADDR 0x9804
#define CSR_IRQ_CONTROLLER_CLEAR_SIZE 1
#define CSR_IRQ_CONTROLLER_VECTOR_ADDR 0x9808
#define CSR_IRQ_CONTROLLER_VECTOR_SIZE 1

/* pcie_phy */
#define CSR_PCIE_PHY_BASE 0x8800
#define CSR_PCIE_PHY_LNK_UP_ADDR 0x8800
#define CSR_PCIE_PHY_LNK_UP_SIZE 1
#define CSR_PCIE_PHY_MSI_ENABLE_ADDR 0x8804
#define CSR_PCIE_PHY_MSI_ENABLE_SIZE 1
#define CSR_PCIE_PHY_BUS_MASTER_ENABLE_ADDR 0x8808
#define CSR_PCIE_PHY_BUS_MASTER_ENABLE_SIZE 1
#define CSR_PCIE_PHY_MAX_REQUEST_SIZE_ADDR 0x880c
#define CSR_PCIE_PHY_MAX_REQUEST_SIZE_SIZE 1
#define CSR_PCIE_PHY_MAX_PAYLOAD_SIZE_ADDR 0x8810
#define CSR_PCIE_PHY_MAX_PAYLOAD_SIZE_SIZE 1

/* constants */
#define DMA_WRITER_INTERRUPT 0
#define UART_INTERRUPT 0
#define DMA_READER_INTERRUPT 1
#define TIMER0_INTERRUPT 1

#endif
